name: Access request to GitHub EM
description: Access request to GitHub EM
title: "Access request to GitHub EM"
labels: ["github-emu","entitlement"]
body:
  - type: markdown
    attributes:
      value: |
        Fill the form to request a new access to this Enterprise Account. The user or group will be assigned to GitHub Enterprise application in Azure Active Directory
  - type: dropdown
    id: type
    attributes:
      label: Object type
      description: Would you like to grant a specific Azure Directory user or a group?
      options:
        - User
        - Group
    validations:
      required: true
  - type: input
    id: user_or_group
    attributes:
      label: User or group name
      description: Indicate the user principal or the group name
      placeholder: ex. Developers
    validations:
      required: true
  - type: dropdown
    id: role
    attributes:
      label: Role
      description: What version of our software are you running?
      options:
        - Enterprise Owner
        - Billing Manager
        - User
        - Restricted User
    validations:
      required: true
