name: Assign Azure resource to app
description: Assign Azure user or group to an Enterprise app

inputs:

  AZURE_CLIENT_ID:
    description: 'The client ID of the service principal'
    required: true

  AZURE_CLIENT_SECRET:
    description: 'The client secret of the service principal'
    required: true

  AZURE_TENANT_ID:
    description: 'The tenant ID of the service principal'
    required: true

  AZURE_APP_NAME:
    description: 'The name of the Azure App'
    required: true

  AZURE_RESOURCE_TYPE:
    description: 'User or Group'
    required: false

  AZURE_RESOURCE_NAME:
    description: 'The user principal or group name of the Azure resource to assign to the app'
    required: true

  AZURE_ROLE_NAME:
    description: 'The name of the application role to assign to the resource'
    required: true

  