name: Entitlement for GitHub

on:
  issues:
    types: [opened, edited, reopened]

env:
  AZURE_APP_NAME: GitHub Enterprise Managed User

jobs:

  parse-issue:
    if: contains(github.event.issue.labels.*.name, 'github-emu')
  
    runs-on: ubuntu-latest

    outputs:
      resourceType: ${{ steps.parse.outputs.resourceType }}
      resourceName: ${{ steps.parse.outputs.resourceName }}
      roleName: ${{ steps.parse.outputs.roleName }}

    steps:
    
    - name: Parse issue
      id: parse
      run: |
          echo "${{ github.event.issue.body }}" >> body.txt
          echo "::set-output name=resourceType::$(awk '/### Resource Type/{getline; getline; print}' body.txt)"
          echo "::set-output name=resourceName::$(awk '/### Resource Name/{getline; getline; print}' body.txt)"
          echo "::set-output name=roleName::$(awk '/### Role/{getline; getline; print}' body.txt)"

  assign-resource:
    runs-on: ubuntu-latest

    needs: parse-issue

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build
      run: |
        cd actions/appRoleAssignment
        npm install
        npx webpack

    - name: Assign Azure resource to app
      uses: ./actions/appRoleAssignment
      with:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

        AZURE_APP_NAME: ${{ env.AZURE_APP_NAME }}
        AZURE_RESOURCE_TYPE: ${{ needs.parse-issue.outputs.resourceType }}
        AZURE_RESOURCE_NAME: ${{ needs.parse-issue.outputs.resourceName }}
        AZURE_ROLE_NAME: ${{ needs.parse-issue.outputs.roleName }}

    - name: Comment on failure
      if: failure()
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Failed!'
          })

    - name: Comment on issue
      if: success()
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Done!'
          })